# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: "Ubuntu 16.04"

variables:
  imageName: $(dockerUser).azurecr.io/iris-train:$(Build.BuildNumber)
  escapeImageName: $(dockerUser).azurecr.io\/iris-train:$(Build.BuildNumber)

steps:
  - script: docker build -f irisTrain/Dockerfile -t $(imageName) irisTrain/.
    displayName: "Build Image"

  - script: |
      docker login -u $(dockerUser) -p $(dockerKey) $(dockerUser).azurecr.io
      docker push $(imageName)
    displayName: "Push to ACR"

  - script: |
      cp -r ./deploy $(Build.ArtifactStagingDirectory)/deploy
    displayName: "Copy Deployment files"

  - script: |
      cp -r pipelines $(Build.ArtifactStagingDirectory)/pipelines
    displayName: "Copy Pipeline Files"

  - script: |
      sed -i 's/#IMAGE_TAG#/$(escapeImageName)/g' $(Build.ArtifactStagingDirectory)/pipelines/*.json
    displayName: "Update Image Tags"

  - script: |
      sed -i 's/#BUILD_NUMBER#/$(Build.BuildNumber)/g' $(Build.ArtifactStagingDirectory)/deploy/*.yaml
    displayName: "Update Deployer Build Number"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts: drop"
