// Generated by https://quicktype.io

type Tester struct {
	Data     []Datum    `json:"data"`    
	Included []Included `json:"included"`
}

type Datum struct {
	Type          string          `json:"type"`         
	ID            string          `json:"id"`           
	Attributes    DatumAttributes `json:"attributes"`   
	Relationships Relationships   `json:"relationships"`
}

type DatumAttributes struct {
	Title   string `json:"title"`  
	Body    string `json:"body"`   
	Created string `json:"created"`
	Updated string `json:"updated"`
}

type Relationships struct {
	Author Author `json:"author"`
}

type Author struct {
	Data Data `json:"data"`
}

type Data struct {
	ID   string `json:"id"`  
	Type string `json:"type"`
}

type Included struct {
	Type       string             `json:"type"`      
	ID         string             `json:"id"`        
	Attributes IncludedAttributes `json:"attributes"`
}

type IncludedAttributes struct {
	Name   string `json:"name"`  
	Age    int64  `json:"age"`   
	Gender string `json:"gender"`
}
