apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pachbot
spec:
  hostNetwork: true
  containers:
    - image: skreter/pachbot:0.1.2
      imagePullPolicy: Always
      command:
        - tail
      args:
        - -f
        - /dev/null
      name: pachbot
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: pipeline-volume
          mountPath: /pipelines
  volumes:
    - name: pipeline-volume
      configMap:
        name: pipelines
  restartPolicy: Never
