apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: pachbot
  name: pachbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pachbot
  template:
    metadata:
      labels:
        run: pachbot
    spec:
      hostNetwork: true
      containers:
        - image: pskreter/pachbot:0.0.6
          imagePullPolicy: Always
          env:
            - name: GITHUB_TOKEN
              value: none
            - name: CLONE_URL
              value: https://github.com/samkreter/KubeconAsia2018.git
            - name: WORK_DIR
              value: ./workRepo
          name: pachbot
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
